title: Ship
subtitle: "A lightweight server develop framework for golang."
description: "A lightweight server develop framework for golang."
author: MuGuangyi
language: en
timezone: UTC

url: https://muguangyi.github.io/ship.io
root: /ship.io/

theme: navy-s

highlight:
  enable: true
  line_number: false

disqus_shortname: ship.io
github: muguangyi/ship